# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm ci
    ng build --prod
    ng build oocx-ng
  displayName: 'npm install and build'

- script: |
    ng test oocx-ng --watch=false --code-coverage --browsers=ChromeHeadless
  displayName: 'run unit tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TESTS-*.xml'
  displayName: 'publish test results'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
  displayName: 'publish code coverage results'

- script: |
    cp README.md dist/oocx-ng
    cp projects/oocx-ng/*.less dist/oocx-ng
    cd dist/oocx-ng
    ../../node_modules/.bin/semantic-release
  displayName: 'publish package'

- task: AzureCLI@1
  inputs:
    azureSubscription: 'startliste-oocx-ng'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob upload-batch --destination \$web --account-name oocxng --source dist/oocx-ng-demo'
  displayName: 'publish demo site to Azure'